config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :user_infoms
  resources :accounts
  resources :atm_machines
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
      
      root 'atm_machines#index'
      

end

app/models/user_infom.rb
class UserInfom < ActiveRecord::Base
     belongs_to :user
    validates :address, :phone_number, :presence => true

end

app/controllers/user_infoms_controller.rb
class UserInfomsController < ApplicationController
  before_action :set_user_infom, only: [:show, :edit, :update, :destroy]

  # GET /user_infoms
  # GET /user_infoms.json
  def index
    @user_infoms = UserInfom.all
  end

  # GET /user_infoms/1
  # GET /user_infoms/1.json
  def show
  end

  # GET /user_infoms/new
  def new
    @user_infom = UserInfom.new
     session[:atm_no] = params[:atm_no] 
  end

  # GET /user_infoms/1/edit
  def edit
    
     session[:atm_no] = params[:atm_no] 
  end

  # POST /user_infoms
  # POST /user_infoms.json
  def create
    @user_infom = UserInfom.new(user_infom_params)

@atm_no = params[:atm_no] 
    respond_to do |format|
      if @user_infom.save
        format.html { redirect_to @user_infom, notice: 'User infom was successfully created.' }
        format.json { render :show, status: :created, location: @user_infom }
      else
        format.html { render :new }
        format.json { render json: @user_infom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_infoms/1
  # PATCH/PUT /user_infoms/1.json
  def update
     @atm_no = params[:atm_no] 
    respond_to do |format|
      if @user_infom.update(user_infom_params)
        format.html { redirect_to @user_infom, notice: 'User infom was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_infom }
      else
        format.html { render :edit }
        format.json { render json: @user_infom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_infoms/1
  # DELETE /user_infoms/1.json
  def destroy
    @user_infom.destroy
    respond_to do |format|
      format.html { redirect_to user_infoms_url, notice: 'User infom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_infom
      @user_infom = UserInfom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_infom_params
      params.require(:user_infom).permit(:name, :address, :phone_number, :email)
    end
end

app/helpers/user_infoms_helper.rb
module UserInfomsHelper
end

app/views/user_infoms/_form.html.erb
<%= form_for(@user_infom) do |f| %>
  <% if @user_infom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_infom.errors.count, "error") %> prohibited this user_infom from being saved:</h2>

      <ul>
      <% @user_infom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_infoms/edit.html.erb
<h1>Editing User Infom</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_infom %> |
<%= link_to 'Back', user_infoms_path %>

app/views/user_infoms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Infoms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone number</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_infoms.each do |user_infom| %>
      <tr>
        <td><%= user_infom.name %></td>
        <td><%= user_infom.address %></td>
        <td><%= user_infom.phone_number %></td>
        <td><%= user_infom.email %></td>
        <td><%= link_to 'Show', user_infom %></td>
        <td><%= link_to 'Edit', edit_user_infom_path(user_infom) %></td>
        <td><%= link_to 'Destroy', user_infom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User infom', new_user_infom_path %>

app/views/user_infoms/new.html.erb
<h1>New User Infom</h1>

<%= render 'form' %>

<%= link_to 'Back', user_infoms_path %>

app/views/user_infoms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user_infom.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user_infom.address %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @user_infom.phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user_infom.email %>
</p>

<%= link_to 'Edit', edit_user_infom_path(@user_infom) %> |
<%= link_to 'Back', user_infoms_path %>